// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRKHcx9dbCxkcM_l-YZV6nUpghnZnW35Q',
    appId: '1:1092063602645:web:967ae30209f838d9df7f5c',
    messagingSenderId: '1092063602645',
    projectId: 'fcm-app-59bcc',
    authDomain: 'fcm-app-59bcc.firebaseapp.com',
    storageBucket: 'fcm-app-59bcc.firebasestorage.app',
    measurementId: 'G-RSX51HG831',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkeNExIqRcCPjifEA824ED51p0qqbmtow',
    appId: '1:1092063602645:android:77fc4136b33e8a1fdf7f5c',
    messagingSenderId: '1092063602645',
    projectId: 'fcm-app-59bcc',
    storageBucket: 'fcm-app-59bcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwEK4kCKopyKiXd3t2-ND_rD2GQpV5ffA',
    appId: '1:1092063602645:ios:cdfda581ee6ffbd5df7f5c',
    messagingSenderId: '1092063602645',
    projectId: 'fcm-app-59bcc',
    storageBucket: 'fcm-app-59bcc.firebasestorage.app',
    iosBundleId: 'com.example.fcmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwEK4kCKopyKiXd3t2-ND_rD2GQpV5ffA',
    appId: '1:1092063602645:ios:cdfda581ee6ffbd5df7f5c',
    messagingSenderId: '1092063602645',
    projectId: 'fcm-app-59bcc',
    storageBucket: 'fcm-app-59bcc.firebasestorage.app',
    iosBundleId: 'com.example.fcmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRKHcx9dbCxkcM_l-YZV6nUpghnZnW35Q',
    appId: '1:1092063602645:web:83f6b7456722d832df7f5c',
    messagingSenderId: '1092063602645',
    projectId: 'fcm-app-59bcc',
    authDomain: 'fcm-app-59bcc.firebaseapp.com',
    storageBucket: 'fcm-app-59bcc.firebasestorage.app',
    measurementId: 'G-E795QQ0LMF',
  );
}
